a = input('Digite algo: ')
print('O tipo primitivo é ', type(a))
print('É alphanumerico ?', a.isalnum())
print('É alfabetico ?', a.isalpha())
print('Tem somente espaços ?', a.isspace())
print('É um número ?', a.isnumeric())
print('Está tudo em maiúsculo ?',a.isupper())
print('Está tudo em minusculo ?', a.islower())
print('Está capitalizado ?', a.istitle())
